### ISSUE TITLE
Crash on world start

### ISSUE THREAD

**Issue by TheControllerCat** [charsmud/TimeTraveler#6]
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 3/10/15 3:54 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at timeTraveler.pasttravel.PastMechanics.saveTime(PastMechanics.java:117)
	at timeTraveler.ticker.Ticker.onPlayerTick(Ticker.java:118)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_28_Ticker_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
	at timeTraveler.pasttravel.PastMechanics.saveTime(PastMechanics.java:117)
	at timeTraveler.ticker.Ticker.onPlayerTick(Ticker.java:118)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_28_Ticker_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
	Entity ID: 2758
	Entity Name: Omnissiah
	Entity's Exact location: 228.50, 76.62, 249.50
	Entity's Block location: World: (228,76,249), Chunk: (at 4,4,9 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Omnissiah'/2758, l='MpServer', x=228.50, y=76.62, z=249.50]]
	Chunk stats: MultiplayerChunkCache: 5, 5
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (228,64,256), Chunk: (at 4,4,0 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8 game time, 8 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 8 total; [EntityChicken['Chicken'/2688, l='MpServer', x=220.50, y=69.00, z=270.50], EntityClientPlayerMP['Omnissiah'/2758, l='MpServer', x=228.50, y=76.62, z=249.50], EntitySheep['Sheep'/2682, l='MpServer', x=230.50, y=64.00, z=240.50], EntitySheep['Sheep'/2683, l='MpServer', x=231.50, y=64.00, z=242.50], EntitySheep['Sheep'/2684, l='MpServer', x=231.50, y=64.00, z=242.50], EntityChicken['Chicken'/2685, l='MpServer', x=217.50, y=69.00, z=268.50], EntityChicken['Chicken'/2686, l='MpServer', x=219.50, y=69.00, z=269.50], EntityChicken['Chicken'/2687, l='MpServer', x=218.50, y=69.00, z=271.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 293726184 bytes (280 MB) / 734527488 bytes (700 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	modJ_StarMinerCore{0.9.8} [StarMinerCore] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	sapmanpack{2.5.1} [SanAndreasPs Manager Pack CORE edition] (SAPManPack-1.7.10-2.5.1.jar) 
	UCHIJAAAA	securitycraft{v1.7.4.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.7.4.1.jar) 
	UCHIJAAAA	betterrecords{1.7.10-1.1.9} [Better Records] (betterrecords-1.7.10-1.1.9.jar) 
	UCHIJAAAA	BiblioCraft{1.11.0} [BiblioCraft] (BiblioCraft[v1.11.0][MC1.7.10].jar) 
	UCHIJAAAA	charsmud_timetraveler{0.1} [Time Traveler] (charsmud_timetraveler-1.2.jar) 
	UCHIJAAAA	claysoldiers{2.0.0-beta.2} [Clay Soldiers Mod] (ClaySoldiersMod-1.7.10-2.0.0-beta.2.jar) 
	UCHIJAAAA	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c.jar) 
	UCHIJAAAA	exnihilo{1.38-46} [Ex Nihilo] (Ex-Nihilo-1.38-46.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
	UCHIJAAAA	HardcoreEnderExpansion{1.8.3} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.3.jar) 
	UCHIJAAAA	headcrumbs{1.6.0} [Headcrumbs] (Headcrumbs-1.6.0.jar) 
	UCHIJAAAA	lasercreepers{1.1b} [Laser Creeper Robot Dino Riders From Space] (Laser Creeper Robot Dino Riders From Space-1.1b.jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10j.jar) 
	UCHIJAAAA	PneumaticCraft{1.11.10-132} [PneumaticCraft] (PneumaticCraft-1.7.10-1.11.10-132-universal.jar) 
	UCHIJAAAA	quiverchevsky{b100} [QuiverBow] (QuiverBow_1.7.10_b100.zip) 
	UCHIJAAAA	modJ_StarMiner{0.9.8bf1} [Starminer Mod] (Starminer1710-0.9.8bf1.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.6.0} [Storage Drawers] (StorageDrawers-1.7.10-1.6.0.jar) 
	UCHIJAAAA	UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3308' Renderer: 'Intel(R) HD Graphics 4000'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3308, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by charsmud** [comment]
Fixed in development version, should be out in a few days.
